name: Auto-approve and Auto-merge Automation PRs

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-approve:
    if: contains(join(fromJson(toJson(github.event.pull_request.labels)).*.name, ','), 'automation')
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  enable-auto-merge:
    needs: auto-approve
    if: contains(join(fromJson(toJson(github.event.pull_request.labels)).*.name, ','), 'automation')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          pull-request-number: ${{ github.event.pull_request.number }}
