name: Gemini Recipes Daily

on:
  schedule:
    - cron: "0 3 * * *" # Daily at 03:00 UTC-5 approx adjust as needed
  workflow_dispatch:
    inputs:
      batch_size:
        description: "Number of recipes to process"
        required: false
        default: "5"
      generate_embeddings:
        description: "Generate embeddings for processed recipes"
        required: false
        default: "true"

concurrency:
  group: gemini-recipes
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  process:
    runs-on: ubuntu-latest
    env:
      BATCH_SIZE: ${{ github.event.inputs.batch_size || '5' }}
      GENERATE_EMBEDDINGS: ${{ github.event.inputs.generate_embeddings || 'true' }}
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      GCP_LOCATION: ${{ vars.GCP_LOCATION || 'global' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade google-genai pyyaml

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node deps
        run: npm ci

      - name: Select batch of recipes
        id: select
        run: |
          python automation/queue/select_batch.py \
            --metadata recipes_metadata.json \
            --processed recipes_vectors.jsonl \
            --count "$BATCH_SIZE" \
            --output-jsonl automation/queue/selection.jsonl \
            --output-files automation/queue/selected_files.txt

      - name: Run Gemini CLI to improve recipes
        if: steps.select.outputs.selected_count != '0'
        uses: google-github-actions/run-gemini-cli@v0.1.10
        with:
          prompt: |
            Completa, normaliza y enriquece sensorial y nutricionalmente las recetas del lote actual.
            Sigue las guías del archivo GEMINI.md. Respeta licencias y fuentes.
            Solo modifica los archivos listados en 'automation/queue/selected_files.txt'.
          settings: |
            {"model":"gemini-1.5-flash","temperature":0.2}
          use_vertex_ai: false
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}

      - name: Generate embeddings (Node, selected only)
        if: env.GENERATE_EMBEDDINGS == 'true' && steps.select.outputs.selected_count != '0'
        run: |
          npx ts-node .github/scripts_ts/vectorize_selected.ts \
            --selected automation/queue/selected_files.txt \
            --metadata recipes_metadata.json \
            --output recipes_vectors.jsonl

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/gemini-recipes/batch-${{ github.run_number }}
          title: "Gemini: batch de recetas ${{ github.run_number }}"
          commit-message: "feat(recipes): batch autoeditado y embeddings (Vertex AI)"
          labels: automation, gemini, embeddings
          body: |
            - Lote: ${{ env.BATCH_SIZE }}
            - Vertex AI: ${{ env.GCP_PROJECT_ID }} / ${{ env.GCP_LOCATION }}
            - Embeddings: ${{ env.GENERATE_EMBEDDINGS }}
          delete-branch: true
